
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BIGGER = 11;
  public static final int SCALARVAR = 2;
  public static final int PLUS = 14;
  public static final int SMALLER = 12;
  public static final int STAR = 17;
  public static final int OSBRACKET = 6;
  public static final int OBRACKET = 8;
  public static final int CBRACKET = 9;
  public static final int NUM = 4;
  public static final int EOF = 0;
  public static final int C = 5;
  public static final int VECTORVAR = 3;
  public static final int CSBRACKET = 7;
  public static final int MINUS = 13;
  public static final int DOT = 19;
  public static final int error = 1;
  public static final int EQ = 10;
  public static final int SC = 15;
  public static final int QM = 18;
  public static final int DIVIDED = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SCALARVAR",
  "VECTORVAR",
  "NUM",
  "C",
  "OSBRACKET",
  "CSBRACKET",
  "OBRACKET",
  "CBRACKET",
  "EQ",
  "BIGGER",
  "SMALLER",
  "MINUS",
  "PLUS",
  "SC",
  "DIVIDED",
  "STAR",
  "QM",
  "DOT"
  };
}

