
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PRINTFUNC = 24;
  public static final int BIGGER = 16;
  public static final int DOUBLE_TYPE = 4;
  public static final int PLUS = 19;
  public static final int SMALLER = 17;
  public static final int WHILE = 23;
  public static final int STAR = 20;
  public static final int IF = 22;
  public static final int OSBRACKET = 9;
  public static final int OGBRACKET = 13;
  public static final int ID = 3;
  public static final int OBRACKET = 11;
  public static final int CBRACKET = 12;
  public static final int NUM = 2;
  public static final int EOF = 0;
  public static final int C = 7;
  public static final int CSBRACKET = 10;
  public static final int MINUS = 18;
  public static final int error = 1;
  public static final int DOT = 8;
  public static final int INT_TYPE = 5;
  public static final int EQ = 15;
  public static final int SGBRACKET = 14;
  public static final int SC = 6;
  public static final int QM = 25;
  public static final int DIVIDED = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUM",
  "ID",
  "DOUBLE_TYPE",
  "INT_TYPE",
  "SC",
  "C",
  "DOT",
  "OSBRACKET",
  "CSBRACKET",
  "OBRACKET",
  "CBRACKET",
  "OGBRACKET",
  "SGBRACKET",
  "EQ",
  "BIGGER",
  "SMALLER",
  "MINUS",
  "PLUS",
  "STAR",
  "DIVIDED",
  "IF",
  "WHILE",
  "PRINTFUNC",
  "QM"
  };
}

