
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PRINTFUNC = 21;
  public static final int BIGGER = 8;
  public static final int DOUBLE_TYPE = 15;
  public static final int PLUS = 11;
  public static final int SMALLER = 9;
  public static final int INT = 13;
  public static final int STAR = 19;
  public static final int OSBRACKET = 3;
  public static final int ID = 14;
  public static final int OBRACKET = 5;
  public static final int CBRACKET = 6;
  public static final int EOF = 0;
  public static final int C = 2;
  public static final int CSBRACKET = 4;
  public static final int MINUS = 10;
  public static final int error = 1;
  public static final int INT_TYPE = 16;
  public static final int EQ = 7;
  public static final int COND = 20;
  public static final int SC = 17;
  public static final int DIVIDED = 18;
  public static final int DOUBLE = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "C",
  "OSBRACKET",
  "CSBRACKET",
  "OBRACKET",
  "CBRACKET",
  "EQ",
  "BIGGER",
  "SMALLER",
  "MINUS",
  "PLUS",
  "DOUBLE",
  "INT",
  "ID",
  "DOUBLE_TYPE",
  "INT_TYPE",
  "SC",
  "DIVIDED",
  "STAR",
  "COND",
  "PRINTFUNC"
  };
}

