
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int KEYWORDS = 23;
  public static final int BIGGER = 17;
  public static final int HC = 5;
  public static final int PLUS = 20;
  public static final int SMALLER = 18;
  public static final int DIGIT = 3;
  public static final int STAR = 21;
  public static final int OSBRACKET = 10;
  public static final int OGBRACKET = 14;
  public static final int OBRACKET = 12;
  public static final int CBRACKET = 13;
  public static final int LETTER = 2;
  public static final int QUOTE = 4;
  public static final int EOF = 0;
  public static final int C = 8;
  public static final int CSBRACKET = 11;
  public static final int DIVIDER = 6;
  public static final int MINUS = 19;
  public static final int error = 1;
  public static final int DOT = 9;
  public static final int EQ = 16;
  public static final int SGBRACKET = 15;
  public static final int SC = 7;
  public static final int DIVIDED = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LETTER",
  "DIGIT",
  "QUOTE",
  "HC",
  "DIVIDER",
  "SC",
  "C",
  "DOT",
  "OSBRACKET",
  "CSBRACKET",
  "OBRACKET",
  "CBRACKET",
  "OGBRACKET",
  "SGBRACKET",
  "EQ",
  "BIGGER",
  "SMALLER",
  "MINUS",
  "PLUS",
  "STAR",
  "DIVIDED",
  "KEYWORDS"
  };
}

